In [3]:
import numpy as np

## 1차원 벡터 인덱싱

In [34]:
x=np.array([0,1,2,3,4])

In [36]:
x[2]

2

In [38]:
x[-1]

4

In [39]:
x[:2]

array([0, 1])

In [40]:
x[2:]

array([2, 3, 4])

## 다차원 벡터 인덱싱

In [43]:
x = np.array([[0,1,2,3],[4,5,6,7]])
x

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [44]:
x[0]

array([0, 1, 2, 3])

In [46]:
x[0][0]

0

In [45]:
x[0,0]

0

In [47]:
x[0,:]

array([0, 1, 2, 3])

In [49]:
x[:,0]

array([0, 4])

In [ ]:
a>5